export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN_SUCCESSFUL = 'RECEIVE_LOGIN_SUCCESSFUL';
export const RECEIVE_LOGIN_FAILURE = 'RECEIVE_LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const REQUEST_CHANGE_PASSWD = 'REQUEST_CHANGE_PASSWD';
export const REQUEST_CHANGE_PASSWD_SUCCESSFUL = 'REQUEST_CHANGE_PASSWD_SUCCESSFUL';
export const REQUEST_CHANGE_PASSWD_FAILURE = 'REQUEST_CHANGE_PASSWD_FAILURE';

// get the person profile action constants
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const SET_TOKEN = 'SET_TOKEN';

export const REQUEST_ASYNCSTORAGE_CHANGE = 'REQUEST_ASYNCSTORAGE_CHANGE';
export const ASYNCSTORAGE_SUCCESS = 'ASYNCSTORAGE_SUCCESS';
export const ASYNCSTORAGE_ERROR = 'ASYNCSTORAGE_ERROR';
export const SUBMIT_CONFIRM = 'SUBMIT_CONFIRM';

export const REQUEST_NEWS = 'REQUEST_NEWS';
export const REQUEST_NEWS_SUCCESSFUL = 'REQUEST_NEWS_SUCCESSFUL';
export const REQUEST_NEWS_FAILURE = 'REQUEST_NEWS_FAILURE';

export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const REQUEST_EVENTS_SUCCESSFUL = 'REQUEST_EVENTS_SUCCESSFUL';
export const REQUEST_EVENTS_FAILURE = 'REQUEST_EVENTS_FAILURE';

export const REQUEST_EVENT = 'REQUEST_EVENT';
export const REQUEST_EVENT_SUCCESSFUL = 'REQUEST_EVENT_SUCCESSFUL';
export const REQUEST_EVENT_FAILURE = 'REQUEST_EVENT_FAILURE';

export const REQUEST_SINGLE_NEWS = 'REQUEST_SINGLE_NEWS';
export const REQUEST_SINGLE_NEWS_SUCCESSFUL = 'REQUEST_SINGLE_NEWS_SUCCESSFUL';
export const REQUEST_SINGLE_NEWS_FAILURE = 'REQUEST_SINGLE_NEWS_FAILURE';

export const REQUEST_EVENTS_HEADLINE_SUCCESSFUL = 'REQUEST_EVENTS_HEADLINE_SUCCESSFUL';

export const REQUEST_EVENTS_ACTIVE_SUCCESSFUL = 'REQUEST_EVENTS_ACTIVE_SUCCESSFUL';
export const REQUEST_ACTIVE_EVENT = 'REQUEST_ACTIVE_EVENT';

// all need atten events action constants
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const GET_ACTIVE_EVENTS = 'GET_ACTIVE_EVENTS';
export const GET_ACTIVE_EVENTS_SUCCESS = 'GET_ACTIVE_EVENTS_SUCCESS';
export const GET_ACTIVE_EVENTS_ERROR = 'GET_ACTIVE_EVENTS_ERROR';

// get the single attend action constants
export const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';
export const GET_SINGLE_EVENT_ERROR = 'GET_SINGLE_EVENT_ERROR';

// get the single news action constants
export const GET_SINGLE_NEWS = 'GET_SINGLE_NEWS';
export const GET_SINGLE_NEWS_SUCCESS = 'GET_SINGLE_NEWS_SUCCESS';
export const GET_SINGLE_NEWS_ERROR = 'GET_SINGLE_NEWS_ERROR';

// get all news action constants
export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

// export const GET_STORAGE_DATA = 'GET_STORAGE_DATA';
// export const GET_STORAGE_DATA_SUCCESS = 'GET_STORAGE_DATA_SUCCESS';
// export const GET_STORAGE_DATA_FAILURE = 'GET_STORAGE_DATA_FAILURE';

export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_ERROR = 'ANSWER_QUESTION_ERROR';

export const INCREMENT_NOW_INDEX = 'INCREMENT_NOW_INDEX';
export const CLEAR_EVERY_TERM_ANSWER_COUNT = 'CLEAR_EVERY_TERM_ANSWER_COUNT';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const FEEDBACK = 'FEEDBACK';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';